# Generated by Django 4.2.3 on 2023-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualmachine',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='genre',
            field=models.CharField(choices=[('L', 'Linux'), ('W', 'Windows')], default='L', max_length=5),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='genreOS',
            field=models.CharField(choices=[('D4', 'Debian'), ('U', 'Ubuntu'), ('WS', 'Windows Server')], default='D4', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='platform',
            field=models.CharField(choices=[('AZ', 'Azure'), ('AWS', 'AWS (Amazon Web Services)'), ('GCP', 'Google Cloud Platform'), ('VMW', 'VMware')], max_length=200),
        ),
    ]
