# Generated by Django 4.2.3 on 2023-07-25 08:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0003_virtualmachine_some_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='active',
        ),
        migrations.RemoveField(
            model_name='virtualmachine',
            name='some_date',
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='pgs_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='virtualmachine',
            name='submition_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='platform',
            field=models.CharField(choices=[('AZ', 'Azure'), ('AWS', 'AWS (Amazon Web Services)'), ('GCP', 'Google Cloud Platform'), ('VMW', 'VMware')], max_length=3),
        ),
    ]
