# Generated by Django 4.2.3 on 2023-07-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0004_remove_virtualmachine_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='genreOS',
            new_name='os',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='submition_date',
            new_name='submission_date',
        ),
        migrations.RenameField(
            model_name='virtualmachine',
            old_name='genre',
            new_name='type',
        ),
    ]
