# Generated by Django 4.2.3 on 2023-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulaire', '0005_rename_genreos_virtualmachine_os_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualmachine',
            name='type',
        ),
        migrations.AlterField(
            model_name='virtualmachine',
            name='os',
            field=models.CharField(choices=[('US', 'Ubuntu Server'), ('WS', 'Windows Server'), ('DB11', 'Debian 11'), ('OL', 'Oracle Linux')], max_length=100),
        ),
    ]
